=== xylo/idea-sql-query-plugin/src/com/kiwisoft/utils/text/syntaxes/syntax.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--W3C Schema generated by XMLSpy v2006 U (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="blockComment">
		<xs:complexType>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="comment1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="begin" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="end" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="*/"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="keyword">
		<xs:complexType mixed="true">
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="lineComment">
		<xs:complexType mixed="true">
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="comment1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="literal">
		<xs:complexType>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="literal1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="begin" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="end" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="noLineBreak" type="xs:boolean" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="markPrevious">
		<xs:complexType>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="function"/>
						<xs:enumeration value="label"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="end" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="("/>
						<xs:enumeration value=":"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="excludeMatch" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:boolean"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="lineStart">
				<xs:simpleType>
					<xs:restriction base="xs:boolean"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="exclude">
				<xs:simpleType>
					<xs:restriction base="xs:boolean"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="markFollowing">
		<xs:complexType>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="begin" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="sequence">
		<xs:complexType mixed="true">
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="syntaxDefinition">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="syntaxRules"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="syntaxRules">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="blockComment" minOccurs="0"/>
				<xs:element ref="lineComment" minOccurs="0"/>
				<xs:element ref="literal" minOccurs="0"/>
				<xs:element ref="markPrevious" minOccurs="0"/>
				<xs:element ref="markFollowing" minOccurs="0"/>
				<xs:element ref="sequence" minOccurs="0"/>
				<xs:element ref="keyword" minOccurs="0"/>
			</xs:choice>
			<xs:attribute name="id" type="xs:string"/>
			<xs:attribute name="escape" type="xs:string"/>
			<xs:attribute name="ignoreCase" type="xs:boolean"/>
			<xs:attribute name="highlightDigits" type="xs:boolean"/>
			<xs:attribute name="terminateChar" type="xs:unsignedByte"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== xylo/idea-sql-query-plugin/src/com/kiwisoft/utils/text/syntaxes/java.xml
<?xml version="1.0"?>

<!--
Copyright (C) 2002-2003 Stefan Stiller

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

Author: Stefan Stiller
Version: $Revision: 1.4 $, $Date: 2004/10/18 18:28:41 $
-->

<syntaxDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="syntax.xsd">
	<syntaxRules ignoreCase="false" highlightDigits="true">
		<blockComment id="comment1" begin="/*" end="*/"/>
		<blockComment id="comment1" begin="/**" end="*/"/>
		<lineComment id="comment1">//</lineComment>

		<literal id="literal1" begin="'" end="'" noLineBreak="true"/>
		<literal id="literal1" begin="&quot;" end="&quot;" noLineBreak="true"/>

		<markPrevious id="label" end=":" lineStart="true" exclude="true"/>

		<sequence id="whitespace"> </sequence>
		<sequence id="whitespace">	</sequence>

		<sequence id="void">(</sequence>
		<sequence id="void">)</sequence>
		<sequence id="void">.*</sequence>
		<sequence id="void">.</sequence>
		<sequence id="void">,</sequence>
		<sequence id="void">;</sequence>
		<sequence id="void">]</sequence>
		<sequence id="void">[</sequence>
		<sequence id="void">?</sequence>
		<sequence id="void">:</sequence>

		<sequence id="operator">=</sequence>
		<sequence id="operator">!</sequence>
		<sequence id="operator">&gt;</sequence>
		<sequence id="operator">&lt;</sequence>
		<sequence id="operator">&gt;=</sequence>
		<sequence id="operator">&lt;=</sequence>
		<sequence id="operator">+</sequence>
		<sequence id="operator">-</sequence>
		<sequence id="operator">/</sequence>
		<sequence id="operator">*</sequence>
		<sequence id="operator">%</sequence>
		<sequence id="operator">&amp;</sequence>
		<sequence id="operator">|</sequence>
		<sequence id="operator">^</sequence>
		<sequence id="operator">~</sequence>
		<sequence id="operator">{</sequence>
		<sequence id="operator">}</sequence>

		<keyword id="keyword1">abstract</keyword>
		<keyword id="keyword1">break</keyword>
		<keyword id="keyword1">case</keyword>
		<keyword id="keyword1">catch</keyword>
		<keyword id="keyword1">continue</keyword>
		<keyword id="keyword1">default</keyword>
		<keyword id="keyword1">do</keyword>
		<keyword id="keyword1">else</keyword>
		<keyword id="keyword1">extends</keyword>
		<keyword id="keyword1">final</keyword>
		<keyword id="keyword1">finally</keyword>
		<keyword id="keyword1">for</keyword>
		<keyword id="keyword1">if</keyword>
		<keyword id="keyword1">implements</keyword>
		<keyword id="keyword1">instanceof</keyword>
		<keyword id="keyword1">native</keyword>
		<keyword id="keyword1">new</keyword>
		<keyword id="keyword1">private</keyword>
		<keyword id="keyword1">protected</keyword>
		<keyword id="keyword1">public</keyword>
		<keyword id="keyword1">return</keyword>
		<keyword id="keyword1">static</keyword>
		<keyword id="keyword1">switch</keyword>
		<keyword id="keyword1">synchronized</keyword>
		<keyword id="keyword1">throw</keyword>
		<keyword id="keyword1">throws</keyword>
		<keyword id="keyword1">transient</keyword>
		<keyword id="keyword1">try</keyword>
		<keyword id="keyword1">volatile</keyword>
		<keyword id="keyword1">while</keyword>

		<keyword id="keyword2">package</keyword>
		<keyword id="keyword2">import</keyword>

		<keyword id="keyword3">boolean</keyword>
		<keyword id="keyword3">byte</keyword>
		<keyword id="keyword3">char</keyword>
		<keyword id="keyword3">class</keyword>
		<keyword id="keyword3">double</keyword>
		<keyword id="keyword3">float</keyword>
		<keyword id="keyword3">int</keyword>
		<keyword id="keyword3">interface</keyword>
		<keyword id="keyword3">long</keyword>
		<keyword id="keyword3">short</keyword>
		<keyword id="keyword3">void</keyword>

		<keyword id="literal2">false</keyword>
		<keyword id="literal2">true</keyword>
		<keyword id="literal2">super</keyword>
		<keyword id="literal2">this</keyword>
		<keyword id="literal2">null</keyword>

		<keyword id="invalid">goto</keyword>
		<keyword id="invalid">const</keyword>
	</syntaxRules>
</syntaxDefinition>
